In [1]:
import numpy as np

In [2]:
a=np.array([32,4,2])
b=np.array([[34,24,5],[42,4,25]])

In [3]:
print(a)
print(a.ndim)
print(a.shape)

print(b)
print(b.ndim)
print(b.shape)

[32  4  2]
1
(3,)
[[34 24  5]
 [42  4 25]]
2
(2, 3)


In [7]:
c=np.array([[[1,2,3],[4,5,6],[64,3,45]]])
print(c)
print(c.ndim)
print(c.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [64  3 45]]]
3
(1, 3, 3)


In [8]:
print(type(a))
print(type(b))
print(type(c))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [10]:
d=np.arange(5)
print(d)

[0 1 2 3 4]


In [12]:
d=np.array([np.arange(5),np.arange(5)])
print(d)

[[0 1 2 3 4]
 [0 1 2 3 4]]


In [16]:
a.sort()

In [17]:
a

array([ 2,  4, 32])

In [18]:
b

array([[34, 24,  5],
       [42,  4, 25]])

In [19]:
b.sort()

In [20]:
b

array([[ 5, 24, 34],
       [ 4, 25, 42]])

In [22]:
b[0][1]

24

In [23]:
a.dtype

dtype('int32')

In [24]:
a.itemsize # how many bites

4

In [25]:
a.size # size i.e. total elements

3

In [26]:
a

array([ 2,  4, 32])

In [27]:
b.size

6

In [28]:
b

array([[ 5, 24, 34],
       [ 4, 25, 42]])

In [29]:
b.itemsize

4

In [30]:
a.nbytes #total memory space = a.size * a.itemsize

12

In [31]:
b.nbytes

24

In [35]:
a,b

(array([ 2,  4, 32]),
 array([[ 5, 24, 34],
        [ 4, 25, 42]]))

In [36]:
a[2]=5
a

array([2, 4, 5])

In [37]:
b[1][0]=90
b

array([[ 5, 24, 34],
       [90, 25, 42]])

In [38]:
b[1,0]

90

In [39]:
b[1,0]=100

In [40]:
b

array([[  5,  24,  34],
       [100,  25,  42]])

In [43]:
b[-2,-2]

24

In [44]:
b[0,]

array([ 5, 24, 34])

In [45]:
b[0]

array([ 5, 24, 34])

In [48]:
b[1:,1:]

array([[25, 42]])

In [49]:
b[1:,]

array([[100,  25,  42]])

In [54]:
b[:,1:]

array([[24, 34],
       [25, 42]])

In [53]:
b

array([[  5,  24,  34],
       [100,  25,  42]])

In [56]:
b[::2,:]

array([[ 5, 24, 34]])

In [57]:
b[:,::2]

array([[  5,  34],
       [100,  42]])

In [58]:
b

array([[  5,  24,  34],
       [100,  25,  42]])

In [60]:
b[:,1]=[88,77]
b

array([[  5,  88,  34],
       [100,  77,  42]])

In [61]:
b[:,1:]=[[1,2],[3,4]]
b

array([[  5,   1,   2],
       [100,   3,   4]])

In [66]:
c=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(c)
print(c.ndim)
print(c.shape)
print(c.itemsize)
print(c.size)
print(c.nbytes)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)
4
12
48


In [67]:
c[0,1,1]

4

In [75]:
z=np.zeros(5)
print(z)
z=np.zeros((2,4,3))
z

[0. 0. 0. 0. 0.]


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [77]:
o=np.ones(6)
print(o)
o=np.ones((2,4,8))
o

[1. 1. 1. 1. 1. 1.]


array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [78]:
f=np.full((2,3,4),9)
f

array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])

In [79]:
np.full_like(o,21)

array([[[21., 21., 21., 21., 21., 21., 21., 21.],
        [21., 21., 21., 21., 21., 21., 21., 21.],
        [21., 21., 21., 21., 21., 21., 21., 21.],
        [21., 21., 21., 21., 21., 21., 21., 21.]],

       [[21., 21., 21., 21., 21., 21., 21., 21.],
        [21., 21., 21., 21., 21., 21., 21., 21.],
        [21., 21., 21., 21., 21., 21., 21., 21.],
        [21., 21., 21., 21., 21., 21., 21., 21.]]])

In [80]:
np.random.rand(2,3,4)

array([[[0.84780042, 0.64731938, 0.98679701, 0.95697493],
        [0.8534913 , 0.92904526, 0.49079905, 0.62113617],
        [0.41391846, 0.29331553, 0.8525843 , 0.17244445]],

       [[0.33013703, 0.1204273 , 0.14815668, 0.27705986],
        [0.42603026, 0.81829307, 0.24532318, 0.2626094 ],
        [0.1777843 , 0.87326515, 0.7599163 , 0.84271946]]])

In [81]:
np.random.random_sample(f.shape)

array([[[0.16015845, 0.17364394, 0.54568764, 0.79959901],
        [0.3845351 , 0.98335687, 0.3733714 , 0.67236895],
        [0.100178  , 0.49451978, 0.0036282 , 0.28971476]],

       [[0.96247219, 0.73284691, 0.01441771, 0.8066317 ],
        [0.23318889, 0.10714241, 0.60295737, 0.95570559],
        [0.61017299, 0.95713061, 0.13342752, 0.40868706]]])

In [88]:
np.random.randint(3,8,size=(2,3,4))

array([[[3, 3, 4, 6],
        [4, 3, 5, 7],
        [5, 6, 7, 5]],

       [[5, 7, 7, 3],
        [6, 5, 3, 4],
        [6, 3, 6, 4]]])

In [99]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [100]:
np.eye(3,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [101]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [106]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

r1=np.repeat(arr,3,axis=0)
r1

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

In [107]:
r1=np.repeat(arr,3,axis=1)
r1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [4, 4, 4, 5, 5, 5, 6, 6, 6]])

In [111]:
x=np.ones((5,5))
x[1:4,1:4]=0
x[2,2]=9
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [112]:
#coping

a=np.array([1,2,3])
b=a
print(a,b)

[1 2 3] [1 2 3]


In [113]:
b[0]=99
a,b

(array([99,  2,  3]), array([99,  2,  3]))

In [114]:
c=a.copy()
c,a

(array([99,  2,  3]), array([99,  2,  3]))

In [115]:
c[0]=1
c,a

(array([1, 2, 3]), array([99,  2,  3]))

In [116]:
a

array([99,  2,  3])

In [123]:
a+2,a-2,a*2,a/2,a//2,a**2,a%2

(array([101,   4,   5]),
 array([97,  0,  1]),
 array([198,   4,   6]),
 array([49.5,  1. ,  1.5]),
 array([49,  1,  1], dtype=int32),
 array([9801,    4,    9]),
 array([1, 0, 1], dtype=int32))

In [124]:
a,b

(array([99,  2,  3]), array([99,  2,  3]))

In [130]:
a+b,a-b,a*b,a/b,a//b,a**b

(array([198,   4,   6]),
 array([0, 0, 0]),
 array([9801,    4,    9]),
 array([1., 1., 1.]),
 array([1, 1, 1]),
 array([-1250178885,           4,          27]))

In [140]:
a.dtype,b.dtype

(dtype('int32'), dtype('int32'))

In [145]:
a1=a.astype('float64')
b1=b.astype('float64')

In [146]:
a1,b1

(array([99.,  2.,  3.]), array([99.,  2.,  3.]))

In [147]:
a1**b1

array([3.69729638e+197, 4.00000000e+000, 2.70000000e+001])

In [148]:
np.sin(a)

array([-0.99920683,  0.90929743,  0.14112001])

In [149]:
np.tan(a)

array([-25.09253498,  -2.18503986,  -0.14254654])

Linear algebra

In [154]:
a=np.random.randint(1,10,size=(2,3))
print(a)

b=np.random.randint(1,10,size=(3,2))
print(b)

[[8 8 6]
 [5 1 6]]
[[9 3]
 [2 6]
 [4 8]]


In [155]:
np.matmul(a,b)

array([[112, 120],
       [ 71,  69]])

In [158]:
#find determinant
x=np.eye(3)
x,np.linalg.det(x)

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 1.0)

In [159]:
c=np.random.randint(1,10,size=(3,3))
c

array([[2, 3, 3],
       [5, 2, 8],
       [2, 1, 4]])

In [160]:
np.linalg.det(c)

-8.999999999999998

In [161]:
c

array([[2, 3, 3],
       [5, 2, 8],
       [2, 1, 4]])

In [162]:
c.T

array([[2, 5, 2],
       [3, 2, 1],
       [3, 8, 4]])

In [163]:
a

array([[8, 8, 6],
       [5, 1, 6]])

In [164]:
a.T

array([[8, 5],
       [8, 1],
       [6, 6]])

In [165]:
#statistics
a

array([[8, 8, 6],
       [5, 1, 6]])

In [173]:
np.mean(a),np.median(a)

(5.666666666666667, 6.0)

In [167]:
np.max(a)

8

In [170]:
np.min(a,axis=1)

array([6, 1])

In [178]:
np.sum(a),np.sum(a,axis=0)

(34, array([13,  9, 12]))

In [179]:
np.average(a,axis=0)

array([6.5, 4.5, 6. ])

In [180]:
#rearrange array

a

array([[8, 8, 6],
       [5, 1, 6]])

In [182]:
a.reshape((3,2))

array([[8, 8],
       [6, 5],
       [1, 6]])

In [184]:
a.reshape((1,6)),a.reshape((6,1))

(array([[8, 8, 6, 5, 1, 6]]),
 array([[8],
        [8],
        [6],
        [5],
        [1],
        [6]]))

In [186]:
a.reshape((2,1,3))

array([[[8, 8, 6]],

       [[5, 1, 6]]])

In [189]:
#vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([9,8,7,6])

np.vstack([v1,v2,v1])

array([[1, 2, 3, 4],
       [9, 8, 7, 6],
       [1, 2, 3, 4]])

In [190]:
#horizontal stack

h1=np.ones((2,4))
h2=np.zeros((2,2))

h1,h2

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[0., 0.],
        [0., 0.]]))

In [193]:
np.hstack((h2,h1,h2))

array([[0., 0., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 0., 0.]])

In [194]:
h1=np.ones((2,4))
h2=np.zeros((1,4))
h1,h2

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[0., 0., 0., 0.]]))

In [195]:
np.vstack((h1,h2))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.]])

In [196]:
a

array([[8, 8, 6],
       [5, 1, 6]])

In [197]:
a>=6

array([[ True,  True,  True],
       [False, False,  True]])

In [198]:
a==6

array([[False, False,  True],
       [False, False,  True]])

In [199]:
a[a==6]

array([6, 6])

In [200]:
a[a>=6]

array([8, 8, 6, 6])

In [201]:
a

array([[8, 8, 6],
       [5, 1, 6]])

In [218]:
np.any(a>6)

True

In [219]:
np.all(a>6)

False

In [222]:
np.any(a>6,axis=0)

array([ True,  True, False])

In [223]:
np.any(a>6,axis=1)

array([ True, False])

In [224]:
a

array([[8, 8, 6],
       [5, 1, 6]])

In [228]:
(a>4) & (a<8)

array([[False, False,  True],
       [ True, False,  True]])

In [230]:
~((a>4) & (a<8))

array([[ True,  True, False],
       [False,  True, False]])

In [229]:
a[(a>4) & (a<8)]

array([6, 5, 6])

In [231]:
a[~((a>4) & (a<8))]

array([8, 8, 1])

In [232]:
a

array([[8, 8, 6],
       [5, 1, 6]])

In [235]:
a.diagonal()

array([8, 1])

In [236]:
a=np.random.randint(1,31,size=(6,5))

In [237]:
a

array([[ 1, 30,  5, 14, 22],
       [ 9, 30,  8, 20, 12],
       [13, 28,  1, 28, 21],
       [15, 25, 20,  8, 19],
       [20, 17, 12, 16, 25],
       [16,  8, 28, 27, 29]])

In [238]:
a[:4,1:].diagonal()

array([30,  8, 28, 19])

In [239]:
a[[0,1,2,3],[1,2,3,4]]

array([30,  8, 28, 19])

In [240]:
a[[0,0,4,4,5,5],[3,4,3,4,3,4]]

array([14, 22, 16, 25, 27, 29])